### ISSUE TITLE
Valheim server crashing

### ISSUE THREAD

**Issue by janjaros** [lloesche/valheim-server-docker#341]
Hi, has anyone experienced this issue since today? Yesterday evening (CET) all was running fine, but today the start of the server is stuck in a loop. There werent any changes done to configuration or anything. 

> valheim_1  | May 12 11:22:15 /supervisord: valheim-server [Message:   BepInEx] Chainloader startup complete
valheim_1  | May 12 11:22:15 /supervisord: valheim-server 05/12/2021 11:22:15: Starting to load scene:start
valheim_1  | May 12 11:22:15 /supervisord: valheim-server Unable to find method SendPreWillRenderCanvases in [UnityEngine.UIModule.dll]UnityEngine.Canvas
valheim_1  | May 12 11:22:15 /supervisord: valheim-server Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
valheim_1  | May 12 11:22:15 /supervisord: valheim-server Obtained 13 stack frames.
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #0  0x007f5ef2a91730 in funlockfile
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #1  0x007f5ef2183fbb in mono_print_method_from_ip
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #2  0x007f5ef22f437c in mono_perfcounter_foreach
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #3  0x007f5ef22f5229 in mono_runtime_invoke
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #4  0x007f5ef3653642 in scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool)
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #5  0x007f5ef36519da in ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool)
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #6  0x007f5ef309bc1f in UI::CanvasManager::WillRenderCanvases()
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #7  0x007f5ef353fb9e in ExecutePlayerLoop(NativePlayerLoopSystem*)
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #8  0x007f5ef353fbe1 in ExecutePlayerLoop(NativePlayerLoopSystem*)
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #9  0x007f5ef354011a in PlayerLoop()
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #10 0x007f5ef36a9aae in PlayerMain(int, char**)
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #11 0x007f5ef28e209b in __libc_start_main
valheim_1  | May 12 11:22:15 /supervisord: valheim-server #12 0x0055a0a4526699 in _start
valheim_1  | 2021-05-12 11:22:17,138 INFO reaped unknown pid 287 (exit status 0)
valheim_1  | May 12 11:22:17 /supervisord: valheim-server /usr/local/bin/valheim-server: line 121:   285 Aborted                 (core dumped) LD_PRELOAD=$SERVER_LD_PRELOAD "$valheim_server" -nographics -batchmode -name "$SERVER_NAME" -port "$SERVER_PORT" -world "$WORLD_NAME" -public "$SERVER_PUBLIC" "${password_args[@]}" $SERVER_ARGS > >(filter) 2>&1
valheim_1  | May 12 11:22:17 /supervisord: valheim-server DEBUG - [281] - Valheim server with PID 285 stopped
valheim_1  | May 12 11:22:17 /supervisord: valheim-server INFO - Releasing PID file /var/run/valheim-server.pid
valheim_1  | May 12 11:22:17 /supervisord: valheim-server INFO - Shutdown complete
valheim_1  | 2021-05-12 11:22:17,149 INFO exited: valheim-server (exit status 0; not expected)
valheim_1  | 2021-05-12 11:22:18,153 INFO spawned: 'valheim-server' with pid 347
valheim_1  | 2021-05-12 11:22:18,154 INFO reaped unknown pid 343 (exit status 0)
valheim_1  | May 12 11:22:18 /supervisord: valheim-server INFO - Running Valheim Server

Thank you for your comments
Have a nice day
Jan

**Comment by janjaros** [comment]
It seems it fixed itself with a new update :-)
